import { IsInt, IsUUID, Min } from 'class-validator';

const INVALID_REQUEST = 'requestId ต้องเป็น UUID และ progressVersion ต้องเป็นจำนวนเต็มตั้งแต่ 1';

export class PlayGameRoundDto {
  /** Generated by the client per round and reused when retrying that round. */
  @IsUUID('all', { message: INVALID_REQUEST })
  requestId!: string;

  @IsInt({ message: INVALID_REQUEST })
  @Min(1, { message: INVALID_REQUEST })
  progressVersion!: number;
}
